ResendReturnedCard/ResendReturnedCard/Models/ResendReturnedCardGetDataResultModel.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Protocols;

namespace ResendReturnedCard.Models
{

    //ResponseCardInfoApi
    public class BaseResponse<T>
    {
        public ResendReturnedCardGetDataResultModel Result { get; set; }
        public string ResultCode { get; set; }
        public string ResultMessage { get; set; }
    }
    public class ResendReturnedCardGetDataResultModel
    {
        public List<sp_CampaignCallList_Resend_Request_Item> Items { get; set; }
        public List<string> card { get; set; }
        public string addres { get; set; }
    }
    public class sp_CampaignCallList_Resend_Request_Item
    {
        public string ID { get; set; }

        public string CardNo { get; set; }
        public string CardName { get; set; }

        public string HomeAddr { get; set; }

        public string CompanyAddr { get; set; }

        public string RegisterAddr { get; set; }

        public string MaskedCarNo => MaskCardNo(CardNo);
        public string MaskCardNo(string cardNumber)
        {
            if(string.IsNullOrEmpty(cardNumber) || cardNumber.Length < 16)
            {
                return cardNumber;
            }
            var maskedPart = new string('*', 8);
            return cardNumber.Substring(0,4) + maskedPart + cardNumber.Substring(12);
        }
    }

    //RequestCardInfoApi
    public class RequestModel
        {
            public ContentModel Content { get; set; }
        }

        public class ContentModel
        {
            public string ID { get; set; }
        }

    public class Step2Model
    {
        public List<string> card { get; set; }
    }
    
    //RequestApplyApi
    public class ResendReturnedCardApplyRequestModel
    {
        public string ID { set; get; }
        public List<string> Cards { get; set; }
        public string AddrType { get; set; }
        public string OtherZip { get; set; }
        public string OtherAddr { get; set; }
    }
    public class HeaderModel
    {
        public string ApplicationName { get; set; }  
    }   
    public class RequestApplyModel
    {
        public ResendReturnedCardApplyRequestModel ResendReturnedCardApplyRequest { get; set; }
        public HeaderModel Header { get; set; }
    }

    //ResponseApplyApi
    public class ResultApplyModel
    {
        public List<string> FailCards { set; get; }
    }
    public class ResponseApplyModel
    {
        public ResultApplyModel ResultApply { get; set; }
        public string ResultCode {  get; set; }
        public string ResultMessage { get; set; }
    }
}

ResendReturnedCard/ResendReturnedCard/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ResendReturnedCard.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ResendReturnedCard/ResendReturnedCard/Controllers/ResendReturnedCardController.cs
using Newtonsoft.Json;
using ResendReturnedCard.Models;
using ResendReturnedCard.Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using static System.Net.WebRequestMethods;

namespace ResendReturnedCard.Controllers
{
    public class ResendReturnedCardController : Controller
    {
        private readonly WebApiInvoker _webApiInvoker;

        public ResendReturnedCardController()
        {
            var httpClient = new HttpClient();
            _webApiInvoker = new WebApiInvoker(httpClient);
        }

        //GET:step1

        public async Task<ActionResult> Step1()
        {
            var cardId = "A900000794";
            var requestModel = new RequestModel
            {
                Content = new ContentModel
                {
                    ID = cardId
                }
            };
            // 調用API獲取資料，回應資料型別 : BaseResponse為泛型類別，包含ResendReturnedCardGetDataResultModel型別資料。("API的URL" , "發送給API的請求資料")
            var response = await _webApiInvoker.PostAsync<BaseResponse<ResendReturnedCardGetDataResultModel>>("http://localhost:3000/api/Apply/QueryReturnedCardInfo", requestModel);

            if (response.ResultCode == "00" && response.Result.Items != null && response.Result.Items.Any())
            {
                // 將資料傳遞視圖
                return View(response.Result);
            }
            else
            {
                // 錯誤或沒有取到資料
                ViewBag.ErrorMessage = string.IsNullOrEmpty(response.ResultMessage) ? "無法獲取卡片資料" : response.ResultMessage;
                return View("Error"); // 跳轉到一個顯示錯誤
            }
        }
        //POST
        [HttpPost]
        public ActionResult Step1(ResendReturnedCardGetDataResultModel model)
        {
            if (ModelState.IsValid && model.addres != null)
            {
            Session["addres"] = model.addres;
            Session["card"] = model.card;
            return RedirectToAction("Step2");
            }
            return RedirectToAction("Step1");
        }


        //GET:step2
        public async Task<ActionResult> Step2()
        {
            var selectedCard = Session["card"] as IEnumerable<string>;
            if (selectedCard == null || !selectedCard.Any()) 
            {
                return RedirectToAction("Step1");
            }
            ViewBag.addres = Session["addres"];
            var cardDataResponse = await GetCardDataFromApi("A900000794");
            var cardData = cardDataResponse.Result.Items;
            var selectedCardData = cardData.Where(card => selectedCard.Contains(card.CardNo)).ToList();
            TempData["addres"] = ViewBag.addres;
            TempData["StepData"] = selectedCardData;
            return View(selectedCardData);
        }
       
        [HttpPost]
        public async Task<ActionResult> Step2(ResendReturnedCardApplyRequestModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var RequestApplyModel = new RequestApplyModel
            {
                ResendReturnedCardApplyRequest = new ResendReturnedCardApplyRequestModel {
                    ID = "A900000794",
                    Cards = model.Cards,
                    AddrType = model.AddrType,
                    OtherZip = model.OtherZip,
                    OtherAddr = model.OtherAddr
                },
                Header = new HeaderModel
                {
                    ApplicationName = "EWEB2"
                }
            };
            ResponseApplyModel responseApplyModel = await _webApiInvoker.PostAsync<ResponseApplyModel>("http://localhost:3000/api/Apply/ResendReturnedCard", RequestApplyModel);
            if(responseApplyModel.ResultCode == "00")
            {
                return RedirectToAction("Step3");
                
            }
            else
            {
                TempData["failMsg"] = "申請失敗";
                return RedirectToAction("Step3");
            }
         }

        //GET:step3
        public ActionResult Step3()
        {
            var stepData = TempData["stepData"] as List<sp_CampaignCallList_Resend_Request_Item>;
            ViewBag.addres = TempData["addres"];
            if (stepData == null || !stepData.Any())
            {
                return RedirectToAction("step2");
            }
            if (TempData["failMsg"] != null)
            {
                ViewBag.failMsg = TempData["failMsg"];
            }
            return View(stepData);
        }
       

        private async Task<BaseResponse<ResendReturnedCardGetDataResultModel>> GetCardDataFromApi(string id)
        {
            var apiUrl = "http://localhost:3000/api/Apply/QueryReturnedCardInfo";
            var resquestBody = new RequestModel
            {
                Content = new ContentModel { ID = id }
            };
            var responses = await _webApiInvoker.PostAsync<BaseResponse<ResendReturnedCardGetDataResultModel>>(apiUrl, resquestBody);
            return responses;
        }
    }
}

    

ResendReturnedCard/ResendReturnedCard/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

ResendReturnedCard/ResendReturnedCard/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

ResendReturnedCard/ResendReturnedCard/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

ResendReturnedCard/ResendReturnedCard/Views/ResendReturnedCard/Step1.cshtml
@model ResendReturnedCard.Models.ResendReturnedCardGetDataResultModel

@using (Html.BeginForm("Step1", "ResendReturnedCard", FormMethod.Post))
{
    <div class="wrapper-container">
        <div class="wrapper">
            <div class="wrapper-mask"></div>
            <div class="outer_container">
                <div class="container no-breadcrumbs">
                    <div class="content transparent step-panel-block">
                        <div class="step">
                            <ul class="list-step list-step--gray">
                                <li class="list-step__item list-step__item--current"><span class="list-step__item-num"></span><span class="list-step__item-title">填寫資料</span></li>
                                <li class="list-step__item"><span class="list-step__item-num"></span><span class="list-step__item-title">確認資料</span></li>
                                <li class="list-step__item"><span class="list-step__item-num"></span><span class="list-step__item-title">申請結果</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="content full-content">
                        <section class="trans-content">
                            <fieldset class="fieldset-block pink-legend">
                                <legend>卡片資料</legend>
                            </fieldset>

                            <table class="new-datatable">
                                <tbody>
                                    <tr>
                                        <th>
                                            <p><span class="red">*</span>申請卡片</p>
                                        </th>
                                        <td>
                                            <ul>

                                                @{ int countCard = 1;}
                                                @foreach (var item in Model.Items)
                                                {
                                                    <li>
                                                        <input class="artfld tickr" id="checkb_card_@(countCard)" name="card" type="checkbox" value="@item.CardNo" />

                                                        <label for="checkb_card_@(countCard)">
                                                            <span><span class="getCheck"></span></span>
                                                            <p class="dis-inline">@item.CardName<br />@item.MaskedCarNo</p>
                                                        </label>
                                                    </li>
                                                    countCard++;
                                                }

                                            </ul>
                                        </td>
                                    </tr>
                                    <tr class="line">
                                        <td colspan="2"></td>
                                    </tr>
                                    <tr>
                                        <th>
                                            <p><span class="red">*</span>卡片寄送地址</p>
                                        </th>
                                        <td>
                                            <ul>
                                                <li>
                                                    <input class="artfld tickr" id="radio_addres_1" name="addres" type="radio" value="@Model.Items[0].HomeAddr" />
                                                    <label for="radio_addres_1"><span><span class="getCheck"></span></span>同現居地址</label>
                                                    <div class="req mthalf mbhalf" data-address-type="1" style="display: none">
                                                        <input class="artfld col-all-min col-7" type="text" placeholder="" value="@Model.Items[0].HomeAddr" disabled />
                                                    </div>
                                                </li>


                                                <li>
                                                    <input class="artfld tickr" id="radio_addres_2" name="addres" type="radio" value="@Model.Items[0].RegisterAddr" />
                                                    <label for="radio_addres_2"><span><span class="getCheck"></span></span>同戶籍地址</label>
                                                    <div class="req mthalf mbhalf mbhalf" data-address-type="2" style="display: none">
                                                        <input class="artfld col-all-min col-7" type="text" placeholder="" value="@Model.Items[0].RegisterAddr" disabled />
                                                    </div>
                                                </li>
                                                <li>
                                                    <input class="artfld tickr" id="radio_addres_3" name="addres" type="radio" value="@Model.Items[0].CompanyAddr" />
                                                    <label for="radio_addres_3"><span><span class="getCheck"></span></span>同公司地址</label>
                                                    <div class="req mthalf mbhalf mbhalf" data-address-type="3" style="display: none">
                                                        <input class="artfld col-all-min col-7" type="text" placeholder="" value="@Model.Items[0].CompanyAddr" disabled />
                                                    </div>
                                                </li>

                                            </ul>
                                        </td>
                                    </tr>



                                </tbody>
                            </table>
                        </section>
                    </div>

                    <div class="content full-content">
                        <section class="trans-content">
                            <table class="new-datatable">
                                <tbody>
                                    <tr>
                                        <td class="reminds red">
                                            <div class="prfy">
                                                <p class="mbhalf">溫馨提醒：</p>
                                                <ol class="disc">
                                                    <li>本功能僅限申請一次，敬請先確認您欲指定的完整地址後再提出申請</li>
                                                    <li>申請重寄後，卡片於近日重新寄至您指定的地址(此設定僅針對本次卡片寄送使用)</li>
                                                    <li>若連同原留存在本行的地址欲變更，請與客服聯絡(02)2528-7776</li>
                                                </ol>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </section>
                    </div>
                    <div class="btn-zone flex-inline-min">
                        <button class="nbtn focus" id="checkRequirment" type="submit">下一步</button>
                    </div>
                    <p class="red">燈箱在這!!!!!!!!!!!!!</p>
                    <!-- 燈箱--><a class="open-lbox" href="#" data-lboxid="#error-1">系統異常</a><a class="open-lbox" href="#" data-lboxid="#error-2">提醒您</a>
                </div>
            </div>
            <div class="lboxed">
                <div class="lbox-block">
                    <div class="error-msg" id="error-1">
                        <div class="close"></div>
                        <h3>系統異常</h3>
                        <div>
                            <p>請與客服聯絡(02)2528-7776</p>
                            <div class="btn-zone"><a class="nbtn focus close" href="#">確定</a></div>
                        </div>
                    </div>

                    <div class="error-msg" id="error-2">
                        <div class="close"></div>
                        <h3>提醒您</h3>
                        <div>
                            <p>親愛的客戶您好，經查系統無卡片退回記錄，若您近日已完成重寄申請，卡片將於近日內寄出，欲修改寄卡地址，請洽客服(02)2528-7776，謝謝。</p>
                            <div class="btn-zone"><a class="nbtn close" href="#">申請進度查詢</a><a class="nbtn focus close" href="#">前往線上辦卡</a></div>
                        </div>
                    </div>
                </div>
            </div>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            <script>
                $(document).ready(function () {
                    $('input[name="addres"]').change(function () {
                        var value = $(this).val();
                        $('input[name="addres"]').next().next().hide();
                        $(this).next().next().show();
                    });
                });
            </script>
        </div>
    </div>
                                                    }

ResendReturnedCard/ResendReturnedCard/Views/ResendReturnedCard/Step2.cshtml
@using ResendReturnedCard.Models
@model IEnumerable<sp_CampaignCallList_Resend_Request_Item>

@using (Html.BeginForm("Step2", "ResendReturnedCard", FormMethod.Post)) {

<div class="wrapper-container">
    <div class="wrapper">
        <div class="wrapper-mask"></div>
        <div class="outer_container">
            <div class="container no-breadcrumbs">
                <div class="content transparent step-panel-block">
                    <div class="step">
                        <ul class="list-step list-step--gray">
                            <li class="list-step__item list-step__item--active"><span class="list-step__item-num"></span><span class="list-step__item-title">填寫資料</span></li>
                            <li class="list-step__item list-step__item--current"><span class="list-step__item-num"></span><span class="list-step__item-title">確認資料</span></li>
                            <li class="list-step__item"><span class="list-step__item-num"></span><span class="list-step__item-title">申請結果</span></li>
                        </ul>
                    </div>
                </div>
                <div class="content">
                    <section class="trans-content">
                        <fieldset class="fieldset-block pink-legend">
                            <legend class="nowrap">基本資料<i class="fieldset-block__icon-collapse"></i></legend>
                            <div class="fieldset-block__body">
                                <div class="confirm-data-block">
                                    <table>
                                        <tbody>
                                            <tr>
                                                <th>
                                                    <p>申請卡片</p>
                                                </th>
                                                <td>
                                                    @foreach (var card in Model) {

                                                           <p class="mbhalf">@card.CardName<br />@card.MaskedCarNo</p>
                                                    }


                                                    


                                                    @* <p class="mbhalf">SPORT悠遊鈦商奶油黃卡(主卡)<br />1234 **** **** 5678</p>
        <p class="mbhalf">DAWHO現金回饋信用卡(主卡)<br />1234 **** **** 5678</p>*@

                                                </td>
                                            </tr>
                                            <tr>
                                                <th>
                                                    <p>卡片寄送地址</p>
                                                </th>
                                                <td>@ViewBag.addres</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </fieldset>
                    </section>
                </div>
                <div class="btn-zone flex-inline-min">
                    <a class="nbtn" href="@Url.Action("Step1","ResendReturnedCard")">上一步</a>
                    <input class="nbtn focus" id="next" type="submit" value="送出" />
                </div>
            </div>
        </div>
    </div>
</div>
}

ResendReturnedCard/ResendReturnedCard/Views/ResendReturnedCard/Step3.cshtml
@using ResendReturnedCard.Models
@model IEnumerable<sp_CampaignCallList_Resend_Request_Item>

<div class="wrapper-container">
    <div class="wrapper">
        <div class="wrapper-mask"></div>
        <div class="outer_container">
            <div class="container no-breadcrumbs">
                <div class="content transparent step-panel-block">
                    <div class="step">
                        <ul class="list-step list-step--gray">
                            <li class="list-step__item list-step__item--active"><span class="list-step__item-num"></span><span class="list-step__item-title">填寫資料</span></li>
                            <li class="list-step__item list-step__item--active"><span class="list-step__item-num"></span><span class="list-step__item-title">確認資料</span></li>
                            <li class="list-step__item list-step__item--current"><span class="list-step__item-num"></span><span class="list-step__item-title">申請結果</span></li>
                        </ul>
                    </div>
                </div>
                <div class="content full-content">
                    <section class="trans-content">
                        <table class="new-datatable">


                            @if (ViewBag.failMsg != null)
                            {
                                <tbody>
                                    <tr>
                                        <td>
                                            <div class="success">
                                                <i class="icon-error"></i>
                                                <p>申請失敗</p>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr class="line">
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td class="reminds">
                                            <p class="center">請與客服聯絡(02)2528-7776</p>
                                        </td>
                                    </tr>
                                </tbody>

                            }
                            else
                            {
                                <tbody>
                                    <tr>
                                        <td>
                                            <div class="success">
                                                <i class="icon-tick"></i>
                                                <p>您已申請成功</p>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            }


                        </table>
                    </section>
                </div>
                <div class="content">
                    <section class="trans-content">
                        <fieldset class="fieldset-block pink-legend">
                            <legend>卡片資料</legend>
                            <div class="confirm-data-block">
                                <table>
                                    <tbody>
                                        <tr>
                                            <th>
                                                <p>申請卡片</p>
                                            </th>
                                            <td>
                                                @foreach (var card in Model)
                                                {<p class="mbhalf">@card.CardName<br />@card.MaskedCarNo</p>
                                            }

                                            </td>
                                        </tr>
                                        <tr>
                                            <th>
                                                <p>卡片寄送地址</p>
                                            </th>
                                            <td>
                                                <p>@ViewBag.addres</p>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </fieldset>
                    </section>
                </div>
                <div class="content transparent">
                    <section class="carousel">
                        <div class="splide">
                            <div class="splide__track">
                                <ul class="splide__list steplist">
                                    <li class="splide__slide">
                                        <a class="splide__link splide__imgbox" href="#" target="_blank">
                                            <figure class="splide__figure">
                                                <img class="splide__img" src="../images/banner/18ec202f6e2000002ef1.jpg" alt="世界是一本書，旅遊成就了人生閱讀" />
                                                <figcaption class="splide__figcaption">世界是一本書，旅遊成就了人生閱讀</figcaption>
                                            </figure>
                                        </a>
                                    </li>
                                    <li class="splide__slide">
                                        <a class="splide__link splide__imgbox" href="#" target="_blank">
                                            <figure class="splide__figure">
                                                <img class="splide__img" src="../images/banner/18f2c96da6d000002c5a.jpg" alt="我阿母的超強工具" />
                                                <figcaption class="splide__figcaption">我阿母的超強工具</figcaption>
                                            </figure>
                                        </a>

                                    </li>
                                    <li class="splide__slide">
                                        <a class="splide__link splide__imgbox" href="#" target="_blank">
                                            <figure class="splide__figure">
                                                <img class="splide__img" src="../images/banner/18ec66ca03a00000a2c2.jpg" alt="寵媽必BUY" />
                                                <figcaption class="splide__figcaption">寵媽必BUY</figcaption>
                                            </figure>
                                        </a>
                                    </li>
                                    <li class="splide__slide">
                                        <a class="splide__link splide__imgbox" href="#" target="_blank">
                                            <figure class="splide__figure">
                                                <img class="splide__img" src="../images/banner/18ec1fdc80100000457e.jpg" alt="分期刷永豐" />
                                                <figcaption class="splide__figcaption">分期刷永豐</figcaption>
                                            </figure>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>